_LICENSE=GFDL GPLv2 LGPL3+
_LICENSE_COMB=multi
_LICENSE_NAME=Multiple (all of): GFDL GPLv2 LGPL3+
_LICENSE_PERMS=dist-mirror dist-sell pkg-mirror pkg-sell auto-accept
_LICENSE_GROUPS=
_LICENSE_NAME_GFDL =GNU Free Documentation License
_LICENSE_PERMS_GFDL =dist-mirror dist-sell pkg-mirror pkg-sell auto-accept
_LICENSE_GROUPS_GFDL =FSF
_LICENSE_DISTFILES_GFDL =libunistring-1.2.tar.xz
_LICENSE_NAME_GPLv2 =GNU General Public License version 2
_LICENSE_PERMS_GPLv2 =dist-mirror dist-sell pkg-mirror pkg-sell auto-accept
_LICENSE_GROUPS_GPLv2 =FSF GPL OSI
_LICENSE_DISTFILES_GPLv2 =libunistring-1.2.tar.xz
_LICENSE_NAME_LGPL3+ =GNU Lesser General Public License version 3 (or later)
_LICENSE_PERMS_LGPL3+ =dist-mirror dist-sell pkg-mirror pkg-sell auto-accept
_LICENSE_GROUPS_LGPL3+ =FSF GPL OSI
_LICENSE_DISTFILES_LGPL3+ =libunistring-1.2.tar.xz
