#!/bin/sh
#
#
# bsdinstall pfSense installation module.
#
# part of pfSense (https://www.pfsense.org)
# Copyright (c) 2023-2024 Rubicon Communications, LLC (Netgate)
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

BSDINSTALL_INC_PATH="/usr/libexec/bsdinstall"
. "${BSDINSTALL_INC_PATH}/pfSense-common"

# Fetch the repository data.
if ! repo_fetch; then
	${BSDDIALOG} --backtitle "$(get_title)" \
	    --title ' pfSense Repository Data Fetch Error ' \
	    --msgbox '\nFailed to fetch the pfSense repository data.\n' 0 0
	exit 1
fi

# Read any messages sent by Netgate.
ELIGIBLE="$(json_read "$(get_info)" '.eligible')"
if [ -n "${ELIGIBLE}" ] && [ "${ELIGIBLE}" = "true" ]; then
	MSGS="$(repo_msgs)"
	if [ -n "${MSGS}" ]; then
		${BSDDIALOG} --backtitle "$(get_title)" \
		    --title ' pfSense Repository Messages ' \
		    --msgbox "\n${MSGS}\n" 0 0
	fi
fi

exit 0
