#!/bin/sh
#
#
# bsdinstall pfSense installation module.
#
# part of pfSense (https://www.pfsense.org)
# Copyright (c) 2023-2024 Rubicon Communications, LLC (Netgate)
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

BSDINSTALL_INC_PATH="/usr/libexec/bsdinstall"
. "${BSDINSTALL_INC_PATH}/pfSense-common"

part_zfs() {

	unset DESTDIR
	unset ZFS_VOLTYPE

	# Select the ZFS Volume type
	if ! zfs_voltype_menu || [ -z "${ZFS_VOLTYPE}" ]; then
		errx "pfSense ZFS Configuration" "\nFailed to select the ZFS volume type.\n "
		exit 1
	fi

	if ! install_zfs_voltype_set "${ZFS_VOLTYPE}"; then
		errx "pfSense partitioning" "\nFailed to set the ZFS volume type.\n "
		exit 1
	fi

	# Select the disk(s)
	if ! disks_select_multi_menu; then
		errx "pfSense partitioning" "\nFailed to select the installation disk.\n "
		exit 1
	fi

	return 0
}

part_ufs() {

	unset DESTDIR

	# Select the disk
	if ! disks_select_menu; then
		errx "pfSense partitioning" "\nFailed to select the installation disk.\n "
		exit 1
	fi

	return 0
}

main_menu() {
	local _arch _pscheme _pscheme_1 _pscheme_2 _diskopt _fstype

	unset FSTYPE
	unset PSCHEME

	_arch="$(uname -p)"
	if [ "${_arch}" = "amd64" ]; then
		_pscheme_1="GPT (compatible with MBR)"
	else
		_pscheme_1="GPT"
	fi
	_pscheme_2="MBR"
	_pscheme="${_pscheme_1}"
	_fstype="ZFS (recommended default)"

	while [ 1 ]; do
		exec 3>&1
		_diskopt="$("${BSDDIALOG}" --backtitle "$(get_title)" \
		    --title " Installation Options " --colors --item-help \
		    --menu "\nPlease select the File System type and the Partition Scheme.\n" \
		     0 0 0 \
		    '>>> Continue' 'Proceed with the installation' 'Continue with the displayed settings' \
		    'F File System' "${_fstype}" 'ZFS (recommended default) or UFS' \
		    'P Partition Scheme' "${_pscheme}" 'Set the Partition Scheme (GPT - GUID Partition Table/MBR - DOS Partitions)' 2>&1 1>&3)" || exit 1
		exec 3>&-

		case "${_diskopt}" in
		"F File System")
			if [ "${_fstype}" = "ZFS (recommended default)" ]; then
				_fstype="UFS"
			else
				_fstype="ZFS (recommended default)"
			fi
			;;
		"P Partition Scheme")
			if [ "${_pscheme}" = "${_pscheme_1}" ]; then
				_pscheme="${_pscheme_2}"
			else
				_pscheme="${_pscheme_1}"
			fi
			;;
		*)
			break
			;;
		esac
	done

	if [ "${_pscheme}" = "${_pscheme_1}" ]; then
		PSCHEME="GPT"
	else
		PSCHEME="MBR"
	fi
	if [ "${_fstype}" = "ZFS (recommended default)" ]; then
		FSTYPE="ZFS"
	else
		FSTYPE="UFS"
	fi

	return 0
}

#
# Main
#

unset DESTDISK
unset FSTYPE
unset PSCHEME

main_menu

case "${PSCHEME}" in
"GPT"|"MBR")
	break
	;;
*)
	errx "pfSense partitioning" "\nInvalid partition scheme.\n "
	exit 1
	;;
esac

case "${FSTYPE}" in
"UFS"|"ZFS")
	break
	;;
*)
	errx "pfSense partitioning" "\nInvalid File System type.\n "
	exit 1
	;;
esac

if ! install_scheme_set "${PSCHEME}"; then
	errx "pfSense partitioning" "\nFailed to set the partition scheme.\n "
	exit 1
fi

if ! install_fstype_set "${FSTYPE}"; then
	errx "pfSense partitioning" "\nFailed to set the File System type.\n "
	exit 1
fi

case "${FSTYPE}" in
"UFS")
	part_ufs
	;;
"ZFS")
	part_zfs
	;;
esac

# $DESTDISK must be set at this point.
if [ -z "${DESTDISK}" ]; then
	errx "pfSense partitioning" "\nFailed to select the installation disk.\n "
	exit 1
fi

# Set the selected disk(s) as the target device on the backend.
if ! install_disk_add "${DESTDISK}"; then
	errx "pfSense partitioning" "\nFailed to save the selected installation disk.\n "
#	exit 1
fi

# Commit changes
if ! install_confirm "${DESTDISK}"; then
	errx "pfSense partitioning" "\nInstallation aborted.\n "
	exit 1
fi

exit 0
