#!/bin/sh
#
#
# bsdinstall pfSense installation module.
#
# part of pfSense (https://www.pfsense.org)
# Copyright (c) 2023-2024 Rubicon Communications, LLC (Netgate)
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

BSDINSTALL_INC_PATH="/usr/libexec/bsdinstall"
. "${BSDINSTALL_INC_PATH}/pfSense-common"

REPO_COUNT="$(repo_count)"

if [ "${REPO_COUNT}" -lt "1" ]; then
	"${BSDDIALOG}" --backtitle "$(get_title)" \
	    --title ' pfSense Repository Error ' \
	    --msgbox '\nInvalid repository count.\n' 0 0
	exit 1
fi

if [ "${REPO_COUNT}" -eq "1" ]; then
	REPO_DEF="$(repo_get_first)"
	if ! repo_setup "${REPO_DEF}"; then
		"${BSDDIALOG}" --backtitle "$(get_title)" \
		    --title ' pfSense Repository Error ' \
		    --msgbox '\nFailed to setup the pfSense repository.\n' 0 0
		exit 1
	fi
	exit 0
fi

_size=$(( ${REPO_COUNT} + 9 ))
if [ "${_size}" -gt 25 ]; then
	_size=25
fi
_menu_size=$(( ${REPO_COUNT} + 1 ))
if [ "${_menu_size}" -gt 20 ]; then
	_menu_size=20
fi

I=0
INFO="$(get_info)"
ELIGIBLE="$(json_read "${INFO}" '.eligible')"

# Is this system eligible for Plus access?
if [ -n "${ELIGIBLE}" ] && [ "${ELIGIBLE}" = "true" ]; then
	VER="Plus"
else
	VER="CE"
fi

while [ "${I}" -lt "${REPO_COUNT}" ]; do

	REPO_ID="$(json_read "${INFO}" ".repos[${I}].id")"
	REPO_NAME="$(json_read "${INFO}" ".repos[${I}].name")"
	REPO_DESC="$(json_read "${INFO}" ".repos[${I}].desc")"

	ROPTS="${ROPTS} \
\"${REPO_ID}-${REPO_NAME}\"    \"${REPO_DESC}\""
	I=$(( ${I} + 1 ))
done

exec 3>&1
SELECTED="$(echo $ROPTS | ${XARGS} -o "${BSDDIALOG}" --clear --colors \
    --backtitle "$(get_title)" \
    --title " Software Version to Install " \
    --menu "\nSelect the version of pfSense ${VER} to install.\n" \
     "${_size}" 65 "${_menu_size}" 2>&1 1>&3)" || exit 1
exec 3>&-

# Check for the result.
if [ -z "${SELECTED}" ]; then
	"${BSDDIALOG}" --backtitle "$(get_title)" \
	    --title ' pfSense Repository Error ' \
	    --msgbox '\nFailed to setup the pfSense repository.\n' 0 0
	exit 1
fi

ID="$(echo "${SELECTED}" | "${CUT}" -f1 -d-)"
if [ -z "${ID}" ]; then
	"${BSDDIALOG}" --backtitle "$(get_title)" \
	    --title ' pfSense Repository Error ' \
	    --msgbox '\nFailed to setup the pfSense repository.\nInvalid ID\n' 0 0
	exit 1
fi
if ! repo_setup "${ID}"; then
	"${BSDDIALOG}" --backtitle "$(get_title)" \
	    --title ' pfSense Repository Error ' \
	    --msgbox '\nFailed to setup the pfSense repository.\n' 0 0
	exit 1
fi

exit 0
