#!/bin/sh
#
# pfSense Installer pfSense-pppoe-linkdown module.
#
# part of pfSense (https://www.pfsense.org)
# Copyright (c) 2015-2024 Rubicon Communications, LLC (Netgate)
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

INSTALL_INC_PATH="/usr/local/libexec/installer"
. "${INSTALL_INC_PATH}/pfSense-common"

IF="${1}"
PROTOCOL="${2}"
LOCAL_IP="${3}"

"${CAT}" <<EOF | "${LOGGER}" -p daemon.info
${0}:
IF=${IF}
PROTOCOL=${PROTOCOL}
LOCAL_IP=${LOCAL_IP}
EOF

case "${PROTOCOL}" in
"inet")
	# Remove the default gateway.
	"${ROUTE}" delete default
	;;
"inet6")
	;;
*)
	echo "Invalid Protocol: ${PROTOCOL}"
	exit 1
esac

if [ -n "${IF}" ]; then
	# Remove the resolv.conf entries.
	"${RESOLVCONF}" -d "${IF}"
fi
