#!/bin/sh
#
# pfSense Installer pfSense-connectivity-check module.
#
# part of pfSense (https://www.pfsense.org)
# Copyright (c) 2023-2024 Rubicon Communications, LLC (Netgate)
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

INSTALL_INC_PATH="/usr/local/libexec/installer"
. "${INSTALL_INC_PATH}/pfSense-common"

network_check() {
	local _error

	/usr/bin/timeout -k 50 40 "${REPOC}" -eIq
	_error="${?}"
	if [ "${_error}" = "0" ] || [ "${_error}" = "99" ]; then
		return 0
	fi
	return 1

	return 0
}

ntp_bootstrap() {
	local _tmpfile

	_tmpfile="$(${MKTEMP})"
	echo > "${_tmpfile}"
	if ! /usr/bin/timeout -k 50 40 /usr/local/sbin/ntpd -g -q \
	    -c "${_tmpfile}" ${NTP_SERVERS}; then
		"${RM}" -f "${_tmpfile}" 2> /dev/null
		echo "Cannot connect to the time servers."
		return 1
	fi

	"${RM}" -f "${_tmpfile}" 2> /dev/null

	return 0
}


#
# Main
#

# Bootstrap the system time.
if ! ntp_bootstrap; then
	echo "Warning: NTP sync failed.  ignoring."
else
	# Create a new certificate after adjust the system clock.
	"${INSTALL_INC_PATH}/pfSense-cert" -c -f -r
fi

# Check the name resolving and Netgate reachability.
if ! network_check; then
	exit 1
fi

exit 0
