#!/bin/sh
# pfSense Installer pfSense-connectivity-check module (Offline Mode).
INSTALL_INC_PATH="/usr/local/libexec/installer"
. "${INSTALL_INC_PATH}/pfSense-common"

network_check() {
    return 0
}

ntp_bootstrap() {
    return 0
}

exit 0
